database:
  client: "mysql"
  max_idle: 10
  max_life_time: "1h"
  max_open_conn: 100
  user: "root"
  password: "jtMpPWhEmK7AYZ"
  host: "localhost"
  name: "dishrank_nu2"
  port: "3306"
  params: "charset=utf8mb4&parseTime=True&loc=Asia%2fTaipei"
  log_enable: 1

concurrentAmount: 2

email:
  api_url: http://domain.ni.com/api/v1/email

rabbitmq:
  domain: amqp://guest:guest@localhost:5672/

log:
  elk: 
    enable: 1
    index: dishrank-test
    url: https://elasticsearch.larvata.tw
  logstash: 
    enable: 0
    url: logstash.mycompany.net:8911
    index: dishrank-test


router:
  port: 5566
